### ISSUE TITLE
Short-term TODO list

### ISSUE THREAD

**Issue by leo-yuriev** [leo-yuriev/libmdbx#64]
1. [x] use CreateFileW() for Windows.
2. [x] Use boot_id to decide whether to rollback unsynced changes when opening the database.
3. [x] "Pickup" mode for opening DB (i.e. use the mode in which the database is already opened by another process).
3. [x] Provide `--help` for `mdbx_test`.
4. [x] Use `statfs()`, `statvfs()` to prevent opening DB in non-exclusive mode over a network.
5. [x] Check/fix build on Elbrus arch (E2K).
6. [x] Check/fix builds for OpenBSD, NetBSD, DragonFly, Solaris.
7. [x] Update driver for ioarena (switch to cmake).
8. [ ] Packaging?
